/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/button/Button.vue')['default']
    Collapse: typeof import('./../components/collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./../components/collapse/CollapseItem.vue')['default']
    Icon: typeof import('./../components/icon/Icon.vue')['default']
  }
}
